trigger: none # attiva la pipeline su push al branch main

pool:
  name: 'ItalyAITask'
  demands:
    - agent.name -equals LinuxAgent

variables:
  azureSubscription: 'AITASKFORCE'
  functionAppName: 'euwdaitaskazf01'
  functionProject: 'SLT16'  # cartella dove stanno i file

steps:
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.11'

- script: |
    python3.11 -m pip install --upgrade pip
    python3.11 -m pip install --no-cache-dir --target=$(Build.ArtifactStagingDirectory)/.python_packages -r $(functionProject)/requirements.txt
  displayName: 'Install dependencies to .python_packages'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(functionProject)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/function.zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: '$(azureSubscription)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)/function.zip'
    runtimeStack: 'PYTHON|3.11'
    deploymentMethod: 'auto'